---
title: "Lab 1"
author: "Amelia Ritger"
date: "1/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(kableExtra)
```

Read in noaa_fisheries.csv data
```{r}
us_landings <- read_csv(here("data","noaa_fisheries.csv")) 
```

Now, make a tidy version of the data frame:

```{r}
landings_tidy <- us_landings %>%
  clean_names() %>%  
  mutate(state = str_to_lower(state), #overwrite column "state" with lowercase names
         afs_name = str_to_lower(afs_name)) %>% #do the same for "afs_name"
  mutate(dollars_num = parse_number(dollars_usd)) #drop non-numeric characters ($,.)
```

Let's just get some information for salmon:
```{r}
salmon_landings <- landings_tidy %>% 
  mutate(afs_clean = str_remove(afs_name, pattern="aggregate")) %>% #remove string "aggregate" everywhere it appears in "afs_name"
  filter(str_detect(afs_clean, pattern = "salmon")) %>%  #keep any rows containing the string "salmon" in "afs_clean"
  separate(afs_clean, into = c("group", "species"), sep = ",") #break "afs_clean" into two new columns where the words are separated by a comma (i.e. salmon and species)
```

Find some grouped summary data:

Find annual total US landings and dollar value (summing across all states) for each TYPE of salmon using `group_by()` and `summarize()` 
```{r}
salmon_summary <- salmon_landings %>% 
  group_by(year, species) %>% #now R knows it should group data by year then species
  summarize(tot_landings = sum(landings_pounds), #for each year and species, total landings
            tot_value = sum(dollars_num) #for each year and species, total $
            )
```

Make a graph! And then export it with `ggsave`
```{r}
salmon_landings_graph <- ggplot(data=salmon_summary, aes(x=year, y=tot_landings)) +
  geom_line(aes(color=species)) +
  theme_minimal()

ggsave(plot=salmon_landings_graph, here("figures","us_salmon_ar.png"),
                                        height=5, width=8)
```

Make a nice kable table:
```{r}
salmon_first_5 <- salmon_summary %>% 
  head(5)

kable(salmon_first_5) %>% 
  kable_styling(bootstrap_options = "striped",
                full_width = FALSE)
```




